[package]
name = "llm-gateway-worker"
version = "1.0.0"
edition = "2021"

[[bin]]
name = "llm-gateway-worker"
path = "src/main.rs"

[dependencies]
llm-gateway-storage = { path = "../storage" }
llm-gateway-audit = { path = "../audit" }
llm-gateway-nats-publisher = { path = "../nats-publisher" }
tokio = { workspace = true }
tracing = { workspace = true }
tracing-subscriber = { workspace = true }
toml = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
chrono = { workspace = true }
uuid = { workspace = true }
futures = "0.3"
async-trait = { workspace = true }
shellexpand = "3"
